name: release wasm

on:
  release:
    types: [created]
    paths:
      - 'cw-burn/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install cargo-run-script
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.74.0
          targets: wasm32-unknown-unknown
          command: install
          args: cargo-run-script --manifest-path cw-burn/Cargo.toml
      - name: Run cargo optimize
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.74.0
          targets: wasm32-unknown-unknown
          command: run-script
          args: optimize --manifest-path cw-burn/Cargo.toml
        env:
          RUST_BACKTRACE: full
      - name: Get release ID
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload optimized wasm
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/*.wasm
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
